### ISSUE TITLE
Use magic platform

### ISSUE THREAD

**Issue by verybigman** [verybigman/bem-grid#51]

**Comment by voischev** [comment]
а в чем magic заключается? ) как я понял там просто про сборку на enb? Или я что-то упустил?

**Comment by verybigman** [comment]
А он там сам понимает что запускать bem или enb

**Comment by voischev** [comment]
Ничего себе. А где почитать про это?

**Comment by verybigman** [comment]
Пока только в коде пакетов, похоже. Нормального ридми нет
