### ISSUE TITLE
row__col_sol: column becomes last for any width

### ISSUE THREAD

**Issue by zxqfox** [verybigman/bem-grid#55]
Am I right that `sol: true` uses wrong mq?

https://github.com/verybigman/bem-grid/blob/master/common.blocks/row/__col/row__col.styl#L69

**Comment by verybigman** [comment]
Why wrong?

**Comment by zxqfox** [comment]
It uses `min-width` and `sol: true` moves cell to the end for all widths.

**Comment by verybigman** [comment]
@zxqfox i don't understand why it bug. sol - small order last. And this mod need for move col to the end of row. What is wrong?:)

**Comment by zxqfox** [comment]
@verybigman I can't nullify `sol` for medium widths. `sol: true, mol: false` doesn't work.

**Comment by verybigman** [comment]
Ok! Now i understand. I fix it:)

**Comment by zxqfox** [comment]
@verybigman Thanks!

**Comment by verybigman** [comment]
@zxqfox if move order classes to only mode this solve your problem? This will be work like visibility classes
