### ISSUE TITLE
upd to bem-core 2.5.* 

### ISSUE THREAD

**Issue by voischev** [verybigman/bem-grid#56]
Чувак пока выпилить резолюшн

**Comment by verybigman** [comment]
Вот взял бы и сделал)))

**Comment by voischev** [comment]
А чего у тебя в мастере? Будущая версия?

**Comment by verybigman** [comment]
У меня вот эта https://github.com/bem/bem-core/releases/tag/v2.5.0

А текущая 2.5.1
