### ISSUE TITLE
не выставляется модификатор no-flexbox у блока row

### ISSUE THREAD

**Issue by kompolom** [verybigman/bem-grid#60]
Проверено в Safari 6.1.6
IE 10 (режим документа ie9)
IE 8

**Comment by verybigman** [comment]
Спасибо! Починим. Сразу напишу. Работало же:)

**Comment by kompolom** [comment]
Есть мысль, почему бы не сделать "деградацию" наоборот. То есть, по умолчанию поведение `flexbox_disabled`, и яваскриптом убирать этот модификатор. Тогда в случае поломки js в старом браузере, верстка не сломается.

**Comment by verybigman** [comment]
Ок, я посмотрю завтра все и починю:)

**Comment by voischev** [comment]
```
var detect = document.createElement('detect');
                console.log(detect);
                detect.style.display = 'flex';
                console.log(detect.style.display);
                detect.style.display !== 'flex' && this.setMod('flexbox', 'disabled');
                console.log(detect.style.display !== 'flex');
``` 

в консоли следующее. 
```
[Log] <detect>​</detect>​
[Log]  // тут пусто!
[Log] true
```

**Comment by zxqfox** [comment]
Видимо, сафари не знает про флексбокс? -webkit-flex пробовал туда сунуть?

**Comment by voischev** [comment]
+1. Должно работать @teraem говорит работает

**Comment by verybigman** [comment]
Хреновый какой-то сафари:)

**Comment by verybigman** [comment]
Все починилось вроде:) я вынес определение flexbox в модификатор row_flexbox_detect, если flexbox находится, то ставиться row_flexbox_detected, ежели нет, то row_flexbox_disabled. @voischev также твою просьбу выполнил, row теперь не инитится по умолчанию.
