### ISSUE TITLE
awesome example page

### ISSUE THREAD

**Issue by verybigman** [verybigman/bem-grid#72]
Build example page with max bem-grid features in action

**Comment by Guria** [comment]
:+1:

**Comment by uradvd85** [comment]
![c users wfrost desktop grid](https://cloud.githubusercontent.com/assets/3129672/6616178/55630734-c8bc-11e4-989f-461ca97c0500.png)

**Comment by Guria** [comment]
Also interested if bem-grid applicable for ui elements positioning. I like flexbox :)

**Comment by verybigman** [comment]
@Guria do you have any example?
