### ISSUE TITLE
элементы в col растягиваются на всю ширину

### ISSUE THREAD

**Issue by kompolom** [verybigman/bem-grid#73]
Заметил что `block` и `inline-block` внутри `row__col` растягиваются на 100%. Мне кажется такое поведение не всегда желательно. 
Возможно это лишнее?
https://github.com/verybigman/bem-grid/blob/master/common.blocks/row/__col/row__col.styl#L14

**Comment by verybigman** [comment]
Спасибо! Посмотрю, что можно с этим сделать
